### ISSUE TITLE
[UI/UX] Clear console button

### ISSUE THREAD

**Issue by charleshong3** [pioneers/pimulator-js#120]
The console becomes very long, we should add a way to clear all the text

**Comment by Thine-Sho** [comment]
Suggestion: clear console button appears after at least 2 messages are displayed in the console.

button matches the style of the "upload field" and "upload code" buttons but still fits the aesthetics of the console tabs. Button only appears when "console" (tab) is active and 'aria-selected' is true and disappears if previous conditionals evaluate to false.
