### ISSUE TITLE
[UI/UX] Change dark mode to CSS

### ISSUE THREAD

**Issue by kevinzhu00** [pioneers/pimulator-js#64]
Currently our java script is in line. For the future we would to move it into a separate file. Additionally, the current java script is very hard-coded and if we add new elements we may have to hard code in the future elements to be compatible with dark mode. Instead, it is like more practical to create a dark mode class with a css variable that we can to future elements.

**Comment by charleshong3** [comment]
JS has been moved to a separate file, but we haven't created a dark mode class with a CSS variable.
